.TH "locale-gen" "8" "Aug 2025" "Gentoo"
.SH "NAME"
locale\-gen - safely compile and install a glibc locale archive
.SH "SYNOPSIS"
.SY locale-gen
.RB [ \-Aqu ]
.RB [ \-c\~\c
.IR config ]
.RB [ \-j\~\c
.IR jobs ]
.RB [ \-p\~\c
.IR prefix ]
.YS
.SY locale-gen
.B \-h
.YS
.SY locale-gen
.B \-V
.YS
.SH "DESCRIPTION"
The locale\-gen utility provides a means by which a system administrator may
conveniently manage the set of locales that are made available to the GNU C
Library. It accomplishes this by acting as a user-friendly frontend for the
standard \fBlocaledef\fR(1) utility, which is used to compile locales and
integrate them into a central archive.
.P
A default installation of Gentoo Linux provides an archive that contains all
supported locales, numbering 500 or more. However, it is typical for an
administrator to require only one or two of these. In that case, the
\fBlocale.gen\fR(5) configuration file may be populated with a list of the
required locales. By default, locale\-gen shall read this file and compile only
the locales that are specified, saving both time and space in the longer term.
.P
If the configuration file is missing, empty, or consists only of comments,
locale\-gen shall act in one of two ways, depending on whether the
\fB\-\-config\fR option was specified. If specified then locale\-gen shall abort
with a suitable diagnostic message. Otherwise, locale\-gen shall act as if the
\fB\-\-all\fR option had been specified.
.SH "OPTIONS"
.TP
\fB\-A\fR, \fB\-\-all\fR
Compile all locales that are officially supported by glibc.
.TP
\fB\-c\fR, \fB\-\-config\fR \fIconfig\fR
Read the given \fIconfig\fR file (defaults to /etc/locale.gen).
.TP
\fB\-d\fR, \fB\-\-prefix\fR \fIprefix\fR
Treat most filesystem paths as being relative to the specified \fIprefix\fR (defaults to / if not a Gentoo Prefix system).
.TP
\fB\-h\fR, \fB\-\-help\fR
Write out a synopsis and summary of the supported options then exit.
.TP
\fB\-j\fR, \fB\-\-jobs\fR \fIjobs\fR
Spawn up to the specified number of \fIjobs\fR to compile locales in parallel (defaults to the number of logical processors).
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress the writing of informational messages to standard output.
.TP
\fB\-u\fR, \fB\-\-update\fR
Suppress the compilation of locales that are already installed (not recommended).
.TP
\fB\-V\fR, \fB\-\-version\fR
Write out some details regarding the program then exit.
.SH "AUTHORS"
Version 3.0 is the work of
.MT kfm@\:plushkava\:.net
Kerin Millar
.ME .
.br
Prior versions are chiefly the work of
.MT vapier@\:google\:.com
Mike Frysinger
.ME .
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/.
.SH "FILES"
.TP
.I /etc/locale.gen
Specifies the locales to be compiled.
.TP
.I /usr/share/i18n/SUPPORTED
A list of officially supported locales.
.TP
.I /usr/lib/locale/locale\-archive
Contains the currently installed locales.
.SH "SEE ALSO"
.BR locale (1),
.BR localedef (1),
.BR locale.gen (5),
.BR locale.conf (5)
