.TH locale.gen 5 "August 2025" "Gentoo"
.SH "NAME"
locale.gen - configuration file for locale\-gen
.SH "DESCRIPTION"
The \fBlocale\-gen\fR(8) utility compiles the locales specified by the \fI/etc/locale.gen\fR file and integrates them into a locale archive.
.P
If present, the file must be comprised by zero or more lines, each of which must be comprised by two fields, separated by one or more <blank> characters. Leading and trailing <blank> characters are permitted. The first field shall be considered as a \fIlocalename\fR and the second field as a \fIcharmap\fR. The \fI/usr/share/i18n/SUPPORTED\fR file contains a complete list of the supported combinations.
.P
Lines that are empty, or which contain only <blank> characters, shall be disregarded. Lines that begin with zero or more <blank> characters, followed by a <number\-sign> character, shall be considered as comments and disregarded. Further, the two fields that form a locale definition may be followed by a comment, provided that its leading <number\-sign> character is enclosed by <blank> characters.
.P
The definition of a <blank> character is that it is either the <tab> or <space> character.
.SH "LOCALE NAMES"
A locale defines a set of cultural conventions, including the writing system, the calendar used, and the means by which dates and numbers are formatted. The GNU C Library employs a locale naming scheme that is based upon the X/Open Common Applications Environment (CAE) Portability Guide Issue 4 (XPG4) specification. A \fIlocalename\fR is composed of between one and four parts.
.P
.RS
.EX
language[_territory][.codeset][@modifier]
.EE
.RE
.P
A complete list of supported \fIlocalename\fR values can be obtained by reading the first column of the \fI/usr/share/i18n/SUPPORTED\fR file. Its values map directly to the names of files residing in the \fI/usr/share/i18n/locales\fR directory, provided that codeset parts are stripped.
.P
Assuming that a given locale is available, it can be effected by assigning its \fIlocalename\fR to the LANG environment variable, provided that a codeset part is incorporated.
.SH "CHARACTER MAPS"
A \fIcharmap\fR, also known as a character set or codeset, is a mapping of character symbols and collating element symbols to actual character encodings, allowing for computers to encode and decode text in a standard way.
.P
A complete list of supported \fIcharmap\fR values can be obtained by reading the second column of the \fI/usr/share/i18n/SUPPORTED\fR file. Its values map directly to the names of files residing in the \fI/usr/share/i18n/charmaps\fR directory, notwithstanding that the names may have a suffix as a consequence of having been compressed.
.P
Given that not all supported values of \fIlocalename\fR incorporate a codeset, the configuration file requires for the second field of each line to define a \fIcharmap\fR.
.SH "EXAMPLES"
.EX
# This is a comment, followed by some valid locale declarations.
en_US.UTF\-8  UTF\-8
zh_CN.UTF\-8  UTF\-8
de_DE.UTF\-8  UTF\-8
hi_IN.UTF\-8  UTF\-8
ja_JP.UTF\-8  UTF\-8 # trailing comments are permitted
.sp
# This is invalid because the localename/charmap combination is unsupported.
en_US        GB2312
.sp
# This is invalid because the charmap field is missing.
en_US
.EE
.SH "FILES"
.TP
.I /etc/locale.gen
The default location of the configuration file.
.TP
.I /usr/share/i18n/SUPPORTED
A list of supported \fIlocalename\fR and \fIcharmap\fR combinations.
.TP
.I /usr/share/i18n/locales
Contains locale definition files that serve as inputs to \fBlocaledef\fR(1).
.TP
.I /usr/share/i18n/charmaps
Contains character map files that serve as inputs to \fBlocaledef\fR(1).
.SH "SEE ALSO"
.BR locale (1),
.BR localedef (1),
.BR locale.conf (5),
.BR locale\-gen (8)
.P
System Interface Definitions, Issue 4, Version 2 (XBD) (1994)
.br
.UR https:\://pubs\:.opengroup\:.org/onlinepubs/009656599/toc\:.pdf
.UE
.P
XPG3\-XPG4 Base Migration Guide, Version 2 (1995).
.br
.UR https://\:archive\:.opengroup\:.org/publications/archive/CDROM/g501\:.pdf
.UE
.P
The Open Group Standard Base Specifications, Issue 8 (POSIX-1.2024).
.br
.UR https://\:pubs\:.opengroup\:.org/onlinepubs/9799919799/basedefs/V1\:_chap03\:.html
.UE
.br
.UR https://\:pubs\:.opengroup\:.org/onlinepubs/9799919799/basedefs/V1\:_chap07\:.html
.UE
.SH "AUTHORS"
.nf
Alastair McKinstry <mckinstry@computer.org>
Mike Frysinger <vapier@gentoo.org>
Kerin Millar <kfm@plushkava.net>
.fi
