.TH "locale-gen" "8" "Aug 2025" "Gentoo"
.SH "NAME"
locale\-gen - safely compile and install a glibc locale archive
.SH "SYNOPSIS"
.SY locale-gen
.RB [ \-A ]
.RB [ \-q ]
.RB [ \-u ]
.RB [ \-c\~\c
.IR config ]
.RB [ \-j\~\c
.IR jobs ]
.RB [ \-p\~\c
.IR prefix ]
.YS
.SY locale-gen
.B \-h
.YS
.SY locale-gen
.B \-V
.YS
.SH "DESCRIPTION"
The locale\-gen utility provides a means by which a system administrator may conveniently manage the set of locales that are made available to the GNU C Library. It accomplishes this by acting as a user-friendly frontend for the standard \fBlocaledef\fR(1) utility, which is used to compile locales and integrate them into a central archive.
.P
A default installation of Gentoo Linux provides an archive that contains all supported locales, numbering 500 or more. However, it is typical for an administrator to require only one or two of these. In that case, the \fI/etc/locale.gen\fR configuration file may be populated with a list of the required locales. By default, locale\-gen shall read this file and compile only the locales that are specified, saving both time and space in the longer term.
.P
If the configuration file is missing, empty, or consists only of comments, locale\-gen shall act in one of two ways, depending on whether the \fB\-c\fR option or LOCALEGEN\_CONFIG environment variable was specified. If neither was specified, locale\-gen shall act as if the \fB\-A\fR option had been specified. Otherwise, locale\-gen shall abort with a suitable diagnostic message.
.SH "OPTIONS"
.TP
\fB\-A\fR, \fB\-\-all\fR
Compile all locales that are officially supported by glibc. Cannot be combined with the \fB-c\fR option.
.TP
\fB\-c\fR, \fB\-\-config\fR \fIconfig\fR
Read the given \fIconfig\fR file (defaults to \fIprefix\fR/etc/locale.gen). The file may be specified as <hyphen-minus>, in which case locale\-gen shall read the configuration from standard input. If the LOCALEGEN\_CONFIG variable is found to be set in the environment, and neither the \fB-A\fR nor \fB-c\fR option is specified, its value shall be taken as a literal \fIconfig\fR file path.
.TP
\fB\-h\fR, \fB\-\-help\fR
Write out a synopsis and summary of the supported options then exit.
.TP
\fB\-j\fR, \fB\-\-jobs\fR \fIjobs\fR
Spawn up to the specified number of \fIjobs\fR to compile locales in parallel (defaults to the number of logical processors).
.TP
\fB\-p\fR, \fB\-\-prefix\fR \fIprefix\fR
Treat FILES as being relative to the specified \fIprefix\fR (defaults to / if not a Gentoo Prefix system). Where explicitly specified, the \fIconfig\fR file shall be exempted from this behaviour.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress the writing of informational messages to standard output.
.TP
\fB\-u\fR, \fB\-\-update\fR
Suppress the compilation of locales that are already installed (not recommended).
.TP
\fB\-V\fR, \fB\-\-version\fR
Write out some details regarding the program then exit.
.SH "FILES"
.TP
.I /etc/locale.gen
Specifies the locales to be compiled.
.TP
.I /usr/share/i18n/SUPPORTED
Specifies the officially supported locales.
.TP
.I /usr/lib/locale/locale\-archive
Contains the currently installed locales.
.TP
.I /usr/share/i18n/locales
Contains locale definition files that serve as inputs to \fBlocaledef\fR(1).
.TP
.I /usr/share/i18n/charmaps
Contains character map files that serve as inputs to \fBlocaledef\fR(1).
.SH "ENVIRONMENT"
.TP
LOCALEGEN\_CONFIG
Defines the path of the \fIconfig\fR file in the absence of the \fB-A\fR and \fB-c\fR options.
.TP
LOCALEGEN\_ALLOW\_UNSUPPORTED
If set as a non-empty string, errors caused by locale\-gen being unable to validate the \fIconfig\fR file shall be conveyed as mere warnings, with the exception of any that concern malformed entries. However, errors caused by \fBlocaledef\fR(1) being unable to compile a given locale shall still be considered as fatal.
.SH "EXIT STATUS"
The exit status shall be 0 under any of these conditions:
.IP \[bu] 2
the \fB\-h\fR and/or \fB\-V\fR options were specified
.IP \[bu] 2
the \fB\-u\fR option was specified but no locales need compiling
.IP \[bu] 2
the options and \fIconfig\fR were validated, the specified locales compiled and the resulting archive installed, without error
.P
Otherwise, the exit status shall be greater than 0.
.SH "AUTHORS"
Version 3.0 is the work of
.MT kfm@\:plushkava\:.net
Kerin Millar
.ME .
.br
Prior versions are chiefly the work of
.MT vapier@\:google\:.com
Mike Frysinger
.ME .
.SH "REPORTING BUGS"
Please report bugs via
.UR https://\:bugs\:.gentoo\:.org/
.UE .
.SH "SEE ALSO"
.BR locale (1),
.BR localedef (1),
.BR locale.gen (5),
.BR locale.conf (5)
